# -*- coding: utf-8 -*-
"""task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12wTnRcqvlTEaYNcCzEkldvcC37Y5DmPk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the iris dataset
iris = sns.load_dataset("iris")
print(iris.head(5))

# Get descriptive statistics of numerical features
print(iris.describe().T)

# Check for missing values
print(iris.isnull().sum())

# Group data by species and calculate some descriptive statistics
species_groups = iris.groupby("species")
print(species_groups.describe())

# Create visualizations
sns.displot(x="sepal_length", hue="species", data=iris)  # Distribution of Sepal Length by Species
sns.pairplot(iris, hue="species")  # Pairwise relationships between features

# Correlation matrix
correlation_matrix = iris.corr(numeric_only=True)
print(correlation_matrix)

# Correlation heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(iris.corr(numeric_only=True), annot=True, cmap="autumn_r")
plt.title("Correlation Heatmap of Iris Dataset")
plt.show()

